name: CI
on:
  push:
    branches:
      - main

jobs:
  testk8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      #- name: Set up Kubectl
      #  uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Configure Kubernetes Cluster
        run: |
          kubectl get pods
