name: CI
on:
  push:
    branches:
      - main

jobs:
  testpr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git config
        run: |
          git config --local user.email "info@kordis-leitstelle.de"
          git config --local user.name "Kordis Release Bot"

      - name: Checkout deploy branch
        run: |
          BRANCH_NAME="prod-deployment"
          git checkout -b $BRANCH_NAME
          if git ls-remote --heads origin $BRANCH_NAME | grep -qw $BRANCH_NAME; then
            echo "Branch exists on origin. Setting up tracking..."
            git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME
          else
            echo "Branch does not exist on origin. Pushing and setting up tracking..."
            git push --set-upstream origin $BRANCH_NAME
          fi
          echo "test" > test.txt
          git add .
          git commit -m "ci(prod): deploy v1.1.1"
          git push
      - name: Update or Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="v1.1.1"
          BRANCH_NAME="prod-deployment"
          TITLE="ci(prod): deploy $RELEASE_TAG"
          PR_TITLE_PREFIX="ci(prod): deploy"
          
          # Check if PR already exists
          EXISTING_PR_NUMBER=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open&head=${GITHUB_REPOSITORY%%/*}:$BRANCH_NAME" | \
               jq -r '.[] | select(.title | startswith("'"$PR_TITLE_PREFIX"'")) | .number' | head -n 1)
           if [[ ! -z "$EXISTING_PR_NUMBER" ]]; then
            echo "Updating existing PR #$EXISTING_PR_NUMBER"
            curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"title\":\"$TITLE\", \"body\": \"This is an automated pull request to deploy [release $RELEASE_TAG](https://github.com/kordis-leitstelle/kordis/releases/tag/$RELEASE_TAG) to production.\"}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/$EXISTING_PR_NUMBER"
          else
              echo "Creating a new PR"
              gh pr create --title "$TITLE" \
                --body "This is an automated pull request to deploy [release $RELEASE_TAG](https://github.com/kordis-leitstelle/kordis/releases/tag/$RELEASE_TAG) to production." \
                --base main \
                --head "$BRANCH_NAME" \
                --reviewer JSPRH,timonmasberg \
            fi
        shell: bash

